name: CI
on:
  push:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v6
      - run: |
          sudo echo 'deb http://security.ubuntu.com/ubuntu xenial-security main' | sudo tee -a /etc/apt/sources.list
          sudo apt-get update -qq
          sudo apt-get install -y libaio1 libevent-dev libssl-dev libssl1.0.0
      - run: sbt -v lint
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-gpg@v3
      - run: |
          sudo echo 'deb http://security.ubuntu.com/ubuntu xenial-security main' | sudo tee -a /etc/apt/sources.list
          sudo apt-get update -qq
          sudo apt-get install -y libaio1 libevent-dev libssl-dev libssl1.0.0
      - name: sbt test
        run: sbt -v test
      - name: sbt scripted
        run: sbt -v scripted
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: "${{ secrets.CW_SCALA_STEWARD_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_FILTER_AUTHOR: "cw-scala-steward"
